import type { Tooltip } from '$lib/types';
import { writable, type Writable, derived, type Readable } from 'svelte/store';
import { menuItems } from './sideMenu';

export const showTooltips: Readable<boolean> = derived(
    menuItems, 
    $menuItems => $menuItems.find(item => item.name === 'tooltips')?.isActive || false
);

export const tooltips: Writable<Tooltip[]> = writable<Tooltip[]>([
	{ element: 'op1fb', message: 'Operator 1 feedback' },
	{ element: 'op2ratio', message: 'Operator 2 harmonicity ratio' },
	{ element: 'op2gain', message: 'Operator 2 gain' },
	{ element: 'op2fb', message: 'Operator 2 feedback' },
	{ element: 'op3ratio', message: 'Operator 3 harmonicity ratio' },
	{ element: 'op3gain', message: 'Operator 3 gain' },
	{ element: 'op3fb', message: 'Operator 3 feedback' },
	{ element: 'loop', message: 'Whether the sample should loop when it reaches the end' },
	{ element: 'loopsize', message: 'Size of the loop. 1 is the entire sample, 0.5 is half the sample etc.' },
	{ element: 'rate', message: 'Playback rate. 1 is normal speed, 2 is twice as fast, 0.5 is half speed etc. Negative numbers play sample in reverse' },
	{ element: 'grainrate', message: 'Grain rate. Number of grains per second' },
	{ element: 'grainsize', message: 'Grain size' },
	{ element: 'grainpan', message: 'Stereo position of grain. Amount of random panning between grains' },
	{ element: 'tablesize', message: 'Size of the wavetable' },
	{ element: 'rows', message: 'Number of rows in the wavetable' },
	{ element: 'xlfo', message: 'LFO rate reading wavetable in horizontal direction' },
	{ element: 'ylfo', message: 'LFO rate reading wavetable in vertical direction' },
	{ element: 'begin', message: 'The position in the sample where playback begins. 0 is the beginning, 0.5 is half way through etc.' },
	{ element: 'end', message: 'The position in the sample where playback ends or loops.' },
	{ element: 'cutoff', message: 'Filter cutoff' },
	{ element: 'res', message: 'Filter resonance' },
	{ element: 'semitone', message: 'Transpose by semitone' },
	{ element: 'octave', message: 'Transpose by octave' },
	{ element: 'vol', message: 'Adjust gain of instrument' },
	{ element: 'pan', message: 'Adjust stereo panning' },
	{ element: 'reverb', message: 'Reverb wet/dry amount' },
	{ element: 'rsize', message: 'Reverb room size' },
	{ element: 'delay', message: 'Delay wet/dry amount' },
	{ element: 'dtime', message: 'Delay time' },
	{ element: 'dcolour', message: 'Delay filter colour' },
	{ element: 'dfb', message: 'Delay feedback' },
	{ element: 'chorus', message: 'Chorus wet/dry amount' },
	{ element: 'chdepth', message: 'Chorus LFO depth' },
	{ element: 'dist', message: 'Distortion amount' },
	{ element: 'crush', message: 'Bitcrusher amount' },
	{ element: 'hicut', message: 'High cut filter frequency' },
	{ element: 'locut', message: 'Low cut filter frequency' },
	{ element: 'measure', message: 'Run the circuit and collapse the qubits' },
	{ element: 'drone', message: 'Sustain notes' },
	{ element: 'vol', message: 'Adjust global volume' },
	{ element: 'env-1-a', message: 'Envelope 1 attack' },
	{ element: 'env-1-d', message: 'Envelope 1 decay' },
	{ element: 'env-1-s', message: 'Envelope 1 sustain' },
	{ element: 'env-1-r', message: 'Envelope 1 release' },
	{ element: 'env-2-a', message: 'Envelope 2 attack. Used for FM modulation envelope' },
	{ element: 'env-2-d', message: 'Envelope 2 decay. Used for FM modulation envelope' },
	{ element: 'env-2-s', message: 'Envelope 2 sustain. Used for FM modulation envelope' },
	{ element: 'env-2-r', message: 'Envelope 2 release. Used for FM modulation envelope' },
	{ element: 'learn', message: 'MIDI learn mode. Turn on and select an outlined element. Move a control on an active MIDI device to map the element to the control. Current mappings are listed in the MIDI side menu' },
	{ element: 'randomise-patching', message: 'Randomise patch cables' },
	{ element: 'clear-patching', message: 'Clear patch cables' },
	{ element: 'global-parameters', message: 'Generic parameters such as octave, gain and panning. Click to randomise'},	
	{ element: 'instrument-parameters', message: 'Instrument specific parameters. Click to randomise'},
	{ element: 'fx-parameters', message: 'Effects parameters, such as reverb and delay. Click to randomise'},
	{ element: 'demo-parameters', message: 'Basic parameters to control the demo synth. Click to randomise'},
]);
